{{- if not .Values.htpasswd.exitingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.htpasswd.username | b64enc | quote }}
  password: {{ .Values.htpasswd.password | b64enc | quote }}
{{- end }}
