apiVersion: batch/v1
kind: Job
metadata:
  name: generate-cert-job
spec:
  template:
    spec:
      containers:
        - name: generate-cert-pod
          image: nginx
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          volumeMounts:
            - name: ssl-folder
              mountPath: /tmp/ssl
          command:
            - bash
            - -c
            - |
              #!/bin/bash
              echo "Regenerate certificate";
              openssl genrsa -out /tmp/ssl/root-ca-key.pem 2048 ;
              openssl req -new -x509 -key /tmp/ssl/root-ca-key.pem -subj "/C=CM/ST=DAIMLER/L=Lisbon/O=ORG/OU=UNIT/CN=localhost" -out /tmp/ssl/root-ca.pem -days 365 ;
              openssl genrsa -out /tmp/ssl/admin-key-temp.pem 2048 ;
              openssl pkcs8 -inform PEM -outform PEM -in /tmp/ssl/admin-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out /tmp/ssl/admin-key.pem ;
              openssl req -new -key /tmp/ssl/admin-key.pem -subj "/C=CM/ST=DAIMLER/O=Lisbon/O=ORG/OU=UNIT/CN=localhost" -out /tmp/ssl/admin.csr ;
              openssl x509 -req -in /tmp/ssl/admin.csr -CA /tmp/ssl/root-ca.pem -CAkey /tmp/ssl/root-ca-key.pem -CAcreateserial -sha256 -out /tmp/ssl/admin.pem -days 365 ;
              openssl genrsa -out /tmp/ssl/client-key-temp.pem 2048 ;
              openssl pkcs8 -inform PEM -outform PEM -in /tmp/ssl/client-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out /tmp/ssl/client-key.pem ;
              openssl req -new -key /tmp/ssl/client-key.pem -subj "/C=CM/ST=DAIMLER/O=Lisbon/O=ORG/OU=UNIT/CN=CLIENT" -out /tmp/ssl/client.csr ;
              openssl x509 -req -in /tmp/ssl/client.csr -CA /tmp/ssl/root-ca.pem -CAkey /tmp/ssl/root-ca-key.pem -CAcreateserial -sha256 -out /tmp/ssl/client.pem -days 365 ;
              rm /tmp/ssl/admin-key-temp.pem ;
              rm /tmp/ssl/admin.csr ;
              rm /tmp/ssl/client-key-temp.pem ;
              rm /tmp/ssl/client.csr ;
      restartPolicy: Never
      volumes:
        - name: ssl-folder
          persistentVolumeClaim:
            claimName: monitoring-certs
  backoffLimit: 1
