image:
  repository: joaopmarques66/hello-world
  tag: 1.1.0
  pullPolicy: IfNotPresent
  pullSecrets: [ ]

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

securityContext:
  runAsNonRoot: true
  runAsUser: 1993

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: my-ingress-controller
  hosts:
    - host: ''
  tls:
    - hosts:
        - ''

resources:
  requests:
    cpu: 125m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 30
