image:
  repository: cloudmobility/hello-world
  tag: 1.0.0
  pullPolicy: IfNotPresent
  pullSecrets: [ ]

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

securityContext:
  runAsNonRoot: true
  runAsUser: 1993

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: my-ingress-controller
  hosts:
    - host: <any-text>-<namespace>-<cluster-name>.cloud.eu1.cloudmobility.io
  tls:
    - hosts:
        - <any-text>-<namespace>-<cluster-name>.cloud.eu1.cloudmobility.io

resources:
  requests:
    cpu: 125m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 30
