image:
  repository: cloudmobility/hello-world
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

securityContext:
  runAsNonRoot: true
  runAsUser: 1993

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: my-ingress-controller
  hosts:
    - host: my-sub-domain.cloud.eu1.cloudmobility.io
  tls:
    - hosts:
        - my-sub-domain.cloud.eu1.cloudmobility.io

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 30
