ingress:
  enabled: true
  ## If you are using the cmy-shared ingress class please see the documentation
  ## With cmy-shared the hostname needs to follow a pattern
  ## https://portal.cloudmobility.io/docs/en/cns/shared-ingress-controller.html
  ingressClassName: cmy-shared
  annotations:
    ## If you want to automatically generate the hostname
    ## use the cloudmobility.io/generate-hostname annotation with true
    cloudmobility.io/generate-hostname: "true"
