apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: stack-secrets
  labels: {{- include "efk.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
{{ ( include "efk.gen-certs" . ) | indent 2 }}
