---
ingress:
  enabled: false
  tls: true
  hostname: ""
  volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  services:
    - serviceName: fluentd
      servicePort: 9880
      path: /fluentd
      #- serviceName: elasticsearch
      #servicePort: 9200
      #path: /elasticsearch
    - serviceName: kibana
      servicePort: 5601
      path: /kibana(/|$)(.*)
  accounts:
    - elasticsearch_username: ""
      elasticsearch_password: ""

kibana:
  kibanaConfig:
    kibana.yml: |
      server.basePath: "/kibana"
      server.rewriteBasePath: false
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  readinessProbe: {}



elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  # disable sysctl init container because this needs to be run as root
  # and on the cluster we don't have that privilege
  sysctlInitContainer:
    enabled: false
  resources:
    requests:
      cpu: "100m"
      memory: "1000Mi"
    limits:
      cpu: "1000m"
      memory: "2000Mi"
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60
  persistence:
    enabled: true
    labels:
      enabled: true
  volumeClaimTemplate:
    storageClassName: standard
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 10Gi
  extraEnvs:
    - name: ELASTIC_PASSWORD
      value: "password"
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: true

fluentd:
  kind: "Deployment"
  livenessProbe:
    initialDelaySeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
  rbac:
    create: false
  podSecurityPolicy:
    enabled: false
    annotations: {}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  resources:
    requests:
      cpu: 400m
      memory: 1000Mi
    limits:
      cpu: 600m
      memory: 1000Mi
  livenessProbe:
    initialDelaySeconds: 40
  readinessProbe:
    initialDelaySeconds: 40
  service:
    type: "ClusterIP"
    annotations: {}
    ports:
      - name: "forwarder"
        protocol: TCP
        containerPort: 24224
      - name: "loginput"
        protocol: TCP
        containerPort: 9880
  dashboards:
    enabled: false
  autoscaling:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: false
  fileConfigs:
    01_sources.conf: |-
      <source>
        @type http
        port 9880
        bind 0.0.0.0
        body_size_limit 32m
        keepalive_timeout 10s
        @label @ELASTIC_INPUT
      </source>
    02_filters.conf: |-
      <label @ELASTIC_INPUT>
        <match **>
          @type relabel
          @label @ELASTIC_DISPATCH
        </match>
      </label>
    03_dispatch.conf: |-
      <label @ELASTIC_DISPATCH>
        <match **>
          @type relabel
          @label @ELASTIC_OUTPUT
        </match>
      </label>

    04_outputs.conf: |-
      <label @ELASTIC_OUTPUT>
        <match **>
          @type elasticsearch
          host "elasticsearch-master"
          port 9200
          @log_level debug
        </match>
        <match **>
          @type stdout
        </match>
      </label>
