---
ingress:
  enabled: false
  tls: true
  hostname: ""
  services:
    - serviceName: fluentd
      servicePort: 9880
      path: /fluentd
    - serviceName: opensearch-dashboards
      servicePort: 5601
      path: /dashboard

opensearch-dashboards:
  rbac:
    create: false
  config:
    opensearch_dashboards.yml: |
      plugins.security.disabled: true
      erver.ssl.enabled: false
      server.basePath: "/dashboard"
      server.rewriteBasePath: true
  readinessProbe: {}

opensearch:
  replicas: 1
  minimumMasterNodes: 1
  networkPolicy:
    create: false
  podSecurityPolicy:
    create: false
    spec:
      privileged: true
  persistence:
    enabled: true
    # Set to false to disable the `fsgroup-volume` initContainer that will update permissions on the persistent disk.
    enableInitChown: false
  resources:
    requests:
      cpu: "250m"
      memory: "100Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"
  config:
    opensearch.yml: |
      plugins.security.disabled: true

fluentd:
  kind: "Deployment"
  rbac:
    create: false
  podSecurityPolicy:
    enabled: false
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  service:
    type: "ClusterIP"
    annotations: {}
    ports:
      - name: "forwarder"
        protocol: TCP
        containerPort: 24224
      - name: "loginput"
        protocol: TCP
        containerPort: 9880
      - name: "probeport"
        protocol: TCP
        containerPort: 9881
  dashboards:
    enabled: false
  autoscaling:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: false
  livenessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 2
  readinessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 2
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
  volumes:
    - name: etcfluentd-main
      configMap:
        name: fluentd-main
        defaultMode: 0777
    - name: etcfluentd-config
      configMap:
        name: fluentd-config
        defaultMode: 0777
  volumeMounts:
    - name: etcfluentd-main
      mountPath: /etc/fluent
    - name: etcfluentd-config
      mountPath: /etc/fluent/config.d/
  fileConfigs:
    01_sources.conf: |-
      <source>
        @type http
        port 9880
        bind 0.0.0.0
        body_size_limit 32m
        keepalive_timeout 10s
        @label @ELASTIC_INPUT
      </source>
      <source>
        @type http
        port 9881
        bind 0.0.0.0
      </source>
    02_filters.conf: |-
      <label @ELASTIC_INPUT>
        <match **>
          @type relabel
          @label @ELASTIC_DISPATCH
        </match>
      </label>
    03_dispatch.conf: |-
      <label @ELASTIC_DISPATCH>
        <match **>
          @type relabel
          @label @ELASTIC_OUTPUT
        </match>
      </label>

    04_outputs.conf: |-
      <label @ELASTIC_OUTPUT>
        <match **>
          @type elasticsearch
          #scheme http
          host "opensearch-cluster-master"
          port 9200
          @log_level debug
          index_name fluentd.${tag}.%Y%m%d
          #user logstash
          #password logstash
          #ssl_verify false
          #ssl_version TLSv1_2
          #logstash_format true
          #enable_ilm true
          flush_interval 10s
        </match>
      </label>
