---
ingress:
  enabled: true
  tls: true
  hostname: ""
  services:
    - serviceName: fluentd
      servicePort: 9880
      path: /fluentd
    # - serviceName: elasticsearch
    #   servicePort: 9881
    #   path: /elasticsearch
    # - serviceName: kibana
    #   servicePort: 9881
    #   path: /kibana
fluentd:
  kind: "Deployment"
  rbac:
    create: false

  # Configure podsecuritypolicy
  # Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  podSecurityPolicy:
    enabled: false
    annotations: {}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 256Mi
  service:
    type: "ClusterIP"
    annotations: {}
    ports:
      - name: "forwarder"
        protocol: TCP
        containerPort: 24224
      - name: "loginput"
        protocol: TCP
        containerPort: 9880
  dashboards:
    enabled: false
  autoscaling:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: false
  fileConfigs:
    01_sources.conf: |-
      <source>
        @type http
        port 9880
        bind 0.0.0.0
        body_size_limit 32m
        keepalive_timeout 10s
      </source>
    02_filters.conf: |-
      <label @KUBERNETES>
        <match kubernetes.var.log.containers.fluentd**>
          @type relabel
          @label @FLUENT_LOG
        </match>

        <filter kubernetes.**>
          @type kubernetes_metadata
          @id filter_kube_metadata
          skip_labels false
          skip_container_metadata false
          skip_namespace_metadata true
          skip_master_url true
        </filter>

        <match **>
          @type relabel
          @label @DISPATCH
        </match>
      </label>
    03_dispatch.conf: |-
      <label @DISPATCH>
        <match **>
          @type relabel
          @label @OUTPUT
        </match>
      </label>

    04_outputs.conf: |-
      <label @OUTPUT>
        <match **>
          @type stdout
          @id stdout
        </match>
      </label>
