---
ingress:
  enabled: false
  tls: true
  hostname: ""
  volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  services:
    - serviceName: fluentd
      servicePort: 9880
      path: /fluentd
      #- serviceName: elasticsearch
      #servicePort: 9200
      #path: /elasticsearch
    # - serviceName: kibana
    #   servicePort: 9881
    #   path: /kibana

elasticsearch:
  replicas: 1
  minimumMasterNodes: 1

fluentd:
  kind: "Deployment"
  rbac:
    create: false
  podSecurityPolicy:
    enabled: false
    annotations: {}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 256Mi
  service:
    type: "ClusterIP"
    annotations: {}
    ports:
      - name: "forwarder"
        protocol: TCP
        containerPort: 24224
      - name: "loginput"
        protocol: TCP
        containerPort: 9880
  dashboards:
    enabled: false
  autoscaling:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: false
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60
  fileConfigs:
    01_sources.conf: |-
      <source>
        @type http
        port 9880
        bind 0.0.0.0
        body_size_limit 32m
        keepalive_timeout 10s
        @label @ELASTIC_INPUT
      </source>
    02_filters.conf: |-
      <label @ELASTIC_INPUT>
        <match **>
          @type relabel
          @label @ELASTIC_DISPATCH
        </match>
      </label>
    03_dispatch.conf: |-
      <label @ELASTIC_DISPATCH>
        <match **>
          @type relabel
          @label @ELASTIC_OUTPUT
        </match>
      </label>

    04_outputs.conf: |-
      <label @ELASTIC_OUTPUT>
        <match **>
          @type elasticsearch
          host "elasticsearch-master"
          port 9200
          @log_level debug
        </match>
        <match **>
          @type stdout
        </match>
      </label>
