{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "hello.fullname" . -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "hello.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.port | default 80 }}
  tls:
  {{- if .Values.ingress.tls }}
    - hosts: 
        - {{ .Values.ingress.hostname | quote }}
  {{- end }}
{{- end }}
