{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "hello.fullname" . -}}
  {{- $isSharedIngressController := eq "cmy-shared" (get .Values.ingress.annotations "kubernetes.io/ingress.class") -}}
  {{- $isAutomaticHostnameEnabled := eq "true" (get .Values.ingress.annotations "cloudmobility.io/generate-hostname") -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "hello.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if and $isSharedIngressController $isAutomaticHostnameEnabled}}
    - host:
    {{else}}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      {{- end }}
      {{- end }}
      http:
        paths:
          - path: {{ $.Values.ingress.path | default "/" }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port | default 80 }}
  tls:
    {{- if and $isSharedIngressController $isAutomaticHostnameEnabled}}
    - hosts:
        - ""
    {{else}}
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
  {{- end }}
