---
{{- if .Values.ingress.enabled }}
{{- $fullName := include "efk.fullname" . }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
  {{- else }}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote}}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          {{- range .Values.ingress.services }}
          - path: {{ .path | quote}}
            pathType: Prefix
            backend:
              serviceName: "{{ $fullName }}-{{ .serviceName }}"
              servicePort: {{ .servicePort }}
          {{- end}}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname | quote}}
      {{- if .Values.ingress.hostname }}
      secretName: "{{ $fullName }}-tls"
  {{- end }}
  {{- end }}
  {{- end }}
