---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-certs
  labels: {{- include "efk.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
