name: linting

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - name: Add helm charts repositories
        run: make ci-add-helm-repos
      - name: Install helm charts
        run: make ci-lint-helm-charts
